package com.onthehill.xaeroworldmapbook.progression;

import java.util.Optional;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import net.minecraft.advancements.predicates.ContextAwarePredicate;
import net.minecraft.advancements.predicates.entity.EntityPredicate;
import net.minecraft.advancements.triggers.SimpleCriterionTrigger;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerPlayer;

/**
 * Custom advancement trigger for the {@code well_traveled} advancement — no
 * vanilla trigger fits "visited N distinct chunks," so this mod defines its
 * own. Fired by {@code XaeroWorldMapBook} once
 * {@link ChunkVisitTracker}'s running distinct-chunk count for a player
 * reaches {@code MapAccessConfig#getChunksRequiredForWellTraveled()} while
 * that player already holds {@code craft_atlas}.
 */
public class WellTraveledTrigger extends SimpleCriterionTrigger<WellTraveledTrigger.TriggerInstance>
{
    /**
     * The single instance of this trigger, registered against the game's
     * criterion-trigger registry by {@code XaeroWorldMapBook.onInitialize()}.
     * Advancement JSON generated by {@code datagen.ModAdvancementProvider}
     * and the server-side call from
     * {@code XaeroWorldMapBook}'s chunk-tracking tick handler both go
     * through this same instance.
     */
    public static final WellTraveledTrigger INSTANCE = new WellTraveledTrigger();

    /**
     * Registers {@link #INSTANCE} against the game's criterion-trigger registry. Called once, unconditionally,
     * from {@code XaeroWorldMapBook.onInitialize()}.
     *
     * @param id This trigger's registry identifier.
     */
    public static void register(Identifier id)
    {
        Registry.register(BuiltInRegistries.TRIGGER_TYPES, id, INSTANCE);
    }

    @Override
    public Codec<TriggerInstance> codec()
    {
        return TriggerInstance.CODEC;
    }

    /**
     * Fires this trigger for the given player, satisfying every listening advancement criterion unconditionally —
     * this trigger has no further condition of its own beyond having been fired at all.
     *
     * @param player The player who just crossed the chunk-travel milestone.
     */
    public void trigger(ServerPlayer player)
    {
        this.trigger(player, instance -> true);
    }

    /**
     * This trigger's condition data. Carries only the standard optional player sub-predicate every criterion
     * trigger supports — this trigger has no criterion-specific fields of its own, since "visited enough distinct
     * chunks" is entirely server-tracked state with nothing meaningful to express in advancement JSON beyond when
     * to check it.
     *
     * @param player Optional standard player sub-predicate.
     */
    public record TriggerInstance(Optional<ContextAwarePredicate> player)
        implements SimpleCriterionTrigger.SimpleInstance
    {
        public static final Codec<TriggerInstance> CODEC = RecordCodecBuilder.create(instance -> instance.group(
            EntityPredicate.ADVANCEMENT_CODEC.optionalFieldOf("player").forGetter(TriggerInstance::player)
        ).apply(instance, TriggerInstance::new));

        @Override
        public Optional<ContextAwarePredicate> player()
        {
            return this.player;
        }
    }
}
